#!/bin/perl

# [after slicing one of the Black Knight's arms off]
# King Arthur: Now stand aside, worthy adversary!
# Black Knight: 'Tis but a scratch!
# King Arthur: A scratch? Your arm's off!
# Black Knight: No, it isn't.
# King Arthur: What's that, then?
# Black Knight: [after a pause] I've had worse.
# King Arthur: You liar!
# Black Knight: Come on, you pansy!

use strict;
use warnings;
use Digest::MD5 qw(md5_hex);

my $filename = "names.txt"
my $hashed_id = "";

open(my $fh, '<', $filename) or die "Could not open '$filename' $!;

while (my $line = <$fh>) {
    chomp $line;
    print "Read: $line\n";
    $hashed_id = md5_hex($line); 
    print "The hash is: $hashed_id\n";
}

close($fh);
