#!/bin/perl

# Sir Bedevere: What makes you think she's a witch?
# Peasant 3: Well, she turned me into a newt!
# Sir Bedevere: A newt?
# Peasant 3: [meekly after a long pause] ... I got better.

print "Hello World!\n";
